from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('auth/', views.auth_page, name='auth_page'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('hospital-volunteering/', views.hospital_volunteering, name='hospital_volunteering'),
    path('workshops/', views.workshops, name='workshops'),
    path('profile/', views.profile_view, name='profile'),
    path('notifications/mark-read/', views.mark_all_read, name='mark_all_read'),
    path('apply/', views.apply, name='apply'),
    path('recommendation/', views.recommendation, name='recommendation'),
    path('workshops/', views.workshops, name='workshops'),
    path('workshops/register/<int:workshop_id>/', views.register_workshop, name='register_workshop'),
    path('student/upload-attendance/<int:app_id>/', views.student_upload_attendance, name='student_upload_attendance'),
    path('activities/', views.activities, name='activities'),
    path('workshops/upload-attendance/<int:reg_id>/', views.student_upload_workshop_attendance, name='student_upload_workshop_attendance'),
    
    # Staff URLs
    path('staff/', views.staff_dashboard, name='staff_dashboard'),
    path('staff/application/<int:app_id>/', views.staff_application_detail, name='staff_application_detail'),
    path('staff/application/<int:app_id>/approve/', views.approve_application, name='approve_application'),
    path('staff/application/<int:app_id>/reject/', views.reject_application, name='reject_application'),
    path('staff/workshops/', views.staff_workshops, name='staff_workshops'),
    path('staff/workshops/add/', views.staff_workshop_add, name='staff_workshop_add'),
    path('staff/workshops/<int:workshop_id>/edit/', views.staff_workshop_edit, name='staff_workshop_edit'),
    path('staff/workshops/<int:workshop_id>/delete/', views.staff_workshop_delete, name='staff_workshop_delete'),
    path('staff/departments/', views.staff_departments, name='staff_departments'),
    path('staff/departments/add/', views.staff_department_add, name='staff_department_add'),
    path('staff/departments/<int:dept_id>/edit/', views.staff_department_edit, name='staff_department_edit'),
    path('staff/departments/<int:dept_id>/delete/', views.staff_department_delete, name='staff_department_delete'),
    path('staff/volunteering-documents/', views.staff_volunteering_documents, name='staff_volunteering_documents'),
    path('staff/attendance/', views.staff_attendance_list, name='staff_attendance_list'),
    path('staff/attendance/<int:sheet_id>/verify/', views.staff_verify_attendance, name='staff_verify_attendance'),
    path('staff/certificates/', views.staff_certificates_list, name='staff_certificates_list'),
    path('staff/certificates/upload/<int:app_id>/', views.staff_upload_certificate, name='staff_upload_certificate'),
    path('staff/certificates/upload-workshop/<int:reg_id>/', views.staff_upload_workshop_certificate, name='staff_upload_workshop_certificate'),
    path('staff/volunteering-documents/<int:doc_id>/delete/', views.staff_delete_volunteering_document, name='staff_delete_volunteering_document'),
    path('staff/export/', views.export_approved_excel, name='export_approved_excel'),
    path('staff/students/', views.staff_students, name='staff_students'),
    path('staff/students/<int:student_id>/', views.staff_student_detail, name='staff_student_detail'),
    path('staff/certificates/<int:cert_id>/edit/', views.staff_edit_certificate, name='staff_edit_certificate'),
    path('staff/certificates/<int:cert_id>/delete/', views.staff_delete_certificate, name='staff_delete_certificate'),
    path('staff/certificates/upload-workshop-attendance/<int:sheet_id>/', views.staff_upload_workshop_cert_from_attendance, name='staff_upload_workshop_cert_from_attendance'),
    path('staff/certificates/verify-workshop-attendance/<int:sheet_id>/', views.staff_verify_workshop_attendance, name='staff_verify_workshop_attendance'),
]