# Generated by Django 6.0.4 on 2026-04-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="grade_year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
