# Generated by Django 6.0.4 on 2026-04-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_studentprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="eligibility",
            field=models.CharField(
                choices=[
                    ("highschool", "High School"),
                    ("undergraduate", "Undergraduate"),
                ],
                default="undergraduate",
                max_length=20,
            ),
        ),
    ]
