# Generated by Django 6.0.4 on 2026-04-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_department_eligibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="area",
            field=models.CharField(
                choices=[
                    ("doha", "Doha"),
                    ("alwakra", "Al Wakra"),
                    ("alkhor", "Al Khor"),
                    ("dukhan", "Dukhan"),
                ],
                default="doha",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="has_evening_shift",
            field=models.BooleanField(default=False),
        ),
    ]
