# Generated by Django 6.0.4 on 2026-04-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_department_area_department_has_evening_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="workshop_pictures/"
            ),
        ),
    ]
