# Generated by Django 6.0.4 on 2026-04-18 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_volunteeringdocument_attendancesheet_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificate",
                to="main.application",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="workshop_registration",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificate",
                to="main.workshopregistration",
            ),
        ),
    ]
