# Generated by Django 6.0.4 on 2026-04-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_certificate_application_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="approved_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_applications",
                to="main.department",
            ),
        ),
    ]
