# Generated by Django 6.0.4 on 2026-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_application_approved_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="workshop_pictures/Discover_your_future_in_healthcare.png",
                null=True,
                upload_to="workshop_pictures/",
            ),
        ),
    ]
