# Generated by Django 6.0.4 on 2026-04-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_workshopattendancesheet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departmentweeklyslot",
            name="total_slots",
        ),
        migrations.AddField(
            model_name="department",
            name="total_slots",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
